language: python

python:
  - 3.5
  - 3.6
  - 3.7

addons:
  apt:
    sources:
    - sourceline: 'deb https://downloads.skewed.de/apt/xenial xenial universe'
      key_url: 'http://ha.pool.sks-keyservers.net/pks/lookup?op=get&search=0x612DEFB798507F25'
    - sourceline: 'deb http://downloads.skewed.de/apt/trusty xenial universe'
    packages:
    - python3-graph-tool
    - python-graph-tool
    - libqt5gui5  # pyqt5>5.11 fails to load the xcb platform plugin without it

install:
  - pip install --upgrade pip setuptools wheel  # install with latest tools
  - pip install --upgrade --upgrade-strategy eager .[dev]  # get latest deps

before_script:
  # As graph-tool cannot be installed by pip, link to the system installation
  # from the virtual environment.
  # TODO: remove the condition once we drop python 2.7.
  - if [[ $(python -c 'import sys; print(sys.version_info[0])') = 3 ]] ;
    then ln -s "/usr/lib/python3/dist-packages/graph_tool" $(python -c "import site; print(site.getsitepackages()[0])");
    else ln -s "/usr/lib/python2.7/dist-packages/graph_tool" $(python -c "import site; print(site.getsitepackages()[0])"); fi

script:
# - make lint
  - make test
  - make doc

after_success:
  - coveralls
